config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: 'pages#index'
  resources :pages, only: [:index], path: ''
  get '/backup', to: 'pages#backup'

  resources :customer_accounts, path: 'customers'
  resources :purchase_orders, path: 'orders' do
    get '/edit/status', to: 'purchase_orders#edit_status'
  end
  scope '/inventory' do
    resources :products, path: 'products'
    resources :inventory_histories, path: 'updates'
  end
  resources :customer_payments, path: 'payments'

  resources :api, only:[] do
    collection do
        get '/po_for_payment', to: 'api#get_purchase_orders_for_customer_payment'
    end
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
    has_many :order_lines, inverse_of: :purchase_order, dependent: :destroy
    has_many :products, through: :order_lines
    has_many :customer_payments
    belongs_to :customer_account

    accepts_nested_attributes_for :order_lines, allow_destroy: true

    validates :customer_account_id, presence: true

    before_create :generate_purchase_order_number
    before_save :sanitize_input

    def outstanding_balance
        total_payments = 0;
        self.customer_payments.each do |customer_payment|
            total_payments += customer_payment.amount_paid
        end
        return self.negotiated_price - total_payments
    end

    private
        def generate_purchase_order_number
            self.po_num = 'PO-' + self.customer_account_id.to_s + '-' + CustomerAccount.find(self.customer_account_id).purchase_orders.count.to_s
        end
        def sanitize_input
            # Discount
            if self.discount_type == 'none'
                self.discount = 0
            else
                if self.discount == 0 || self.discount == nil
                    self.discount_type =='none'
                    self.discount = 0
                end
            end

            # Status
            if self.status == 'unfulfilled'
                self.date_fulfilled = nil
            elsif self.status == 'fulfilled' && self.date_fulfilled == nil
                self.status = 'unfulfilled'
                self.date_fulfilled = nil
            end
        end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
    before_action :authenticate_user!, :get_records, only: [:index, :new, :edit]

    def index
    end
    def new
        @purchase_order = PurchaseOrder.new
    end
    def create
        @purchase_order = PurchaseOrder.new(purchase_order_params)
        if @purchase_order.save
            create_inventory_histories(@purchase_order)
            redirect_to(purchase_order_path(@purchase_order))

            flash_content = [
                "This purchase order was successfully created. Its assigned identifier is <b>#{@purchase_order.po_num}</b>.",
                "#{@purchase_order.order_lines.count} Inventory #{@purchase_order.order_lines.count != 1 ? 'Updates were' : 'Update was' } created."
            ]

            if @purchase_order.payment_terms == 'paid'
                flash_content.push("Since this purchase order was paid on purchase, a Customer Payment record was also created.")
                create_customer_payment(@purchase_order)
            end

            flash[:notice] = {type: 'success', header: 'Successfully created new Purchase Order!', content: flash_content}
        else
            render :new
        end
    end
    def show
        @purchase_order = PurchaseOrder.find(params[:id])
    end
    def edit
        @purchase_order = PurchaseOrder.find(params[:id])
    end
    def edit_status
        @purchase_order = PurchaseOrder.find(params[:purchase_order_id])
    end
    def update
        @purchase_order = PurchaseOrder.find(params[:id])
        if @purchase_order.update(purchase_order_params)
            redirect_to(purchase_order_path(@purchase_order))
        else
            render :edit
        end
    end

    private
        def get_records
            @purchase_orders = PurchaseOrder.all
            @customer_accounts = CustomerAccount.all
            @products = Product.all
        end
        def purchase_order_params
            params.require(:purchase_order).permit!
        end
        def create_inventory_histories(purchase_order)
            purchase_order.order_lines.each do |order_line|
                inventory_history = InventoryHistory.new(
                    date_changed: purchase_order.purchase_date,
                    action_type: 'out',
                    quantity: order_line.quantity,
                    product_id: order_line.product_id,
                    order_line_id: order_line.id
                )
                inventory_history.save
            end
        end

        # Create Customer Payment if fully paid.
        def create_customer_payment(purchase_order)
            if purchase_order.payment_terms == 'paid'
                customer_payment = CustomerPayment.new(
                    payment_date: purchase_order.purchase_date,
                    amount_paid: purchase_order.negotiated_price,
                    customer_account_id: purchase_order.customer_account.id,
                    purchase_order_id: purchase_order.id
                )
                customer_payment.save
            end
        end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_header.html.erb
<div class = 'ui vertical segment container-header'>
    <h1>Purchase Orders</h1>
    <div class = 'ui compact menu header-menu'>
        <a class = 'item' href = <%= purchase_orders_path %>>All Purchase Orders</a>
        <a class = 'item' href = <%= new_purchase_order_path %>><i class = 'add icon'></i>New</a>
    </div>
</div>

app/views/purchase_orders/_order_line_fields.html.erb
<tr class = 'order-line-item'>
    <td class = 'col-checkbox'>
        <div id = 'check-itemSelect' class = 'ui fitted checkbox'>
            <input type = 'checkbox'>
            <label></label>
        </div>
    </td>
    <td class = 'col-particulars'></td>
    <td class = 'col-unit-price'></td>
    <td class = 'col-qty'></td>
    <td class = 'col-order-price'></td>
    <td style = 'display: none;'>
        <%= order_line.text_field :product_id, class: 'main-form product-id', hidden: true %>
        <%= order_line.text_field :quantity, class: 'main-form qty', hidden: true %>
        <%= order_line.text_field :order_price, class: 'main-form order-price', hidden: true %>
        <%= link_to_remove_association 'Remove', order_line, wrapper_class: 'order-line-item', style: 'display: none;', id: 'button-removeItem' %>
    </td>
</tr>

app/views/purchase_orders/edit.html.erb
<%= render 'header' %>
<div class = 'container-content view-edit'>
    <div class = 'ui attached message'>
        <div class = 'header'>Edit Purchase Order</div>
    </div>
    <%= render 'form' %>
</div>

app/views/purchase_orders/edit_status.html.erb
<%= render 'header' %>
<div class = 'container-content view-edit-status'>
    <div class = 'ui attached message'>
        <div class = 'header'>Edit Purchase Order Status</div>
    </div>
    <%= form_for @purchase_order, method: :patch, html: {class: 'ui form'} do |purchase_order| %>
        <div class = 'ui attached segment'>
            <div class = 'field'>
                <label>Purchase Order ID</label>
                <span><%= @purchase_order.po_num %></span>
            </div>
        </div>
        <div class = 'ui attached segment'>
            <div class = 'field'>
                <label>Status</label>
                <div id = 'select-status' class = 'ui fluid floating dropdown button' data-value = 'unfulfilled'>
                    <span class = 'text'>Unfulfilled</span>
                    <i class = 'dropdown icon'></i>
                    <div class = 'menu'>
                        <div class = 'item' data-value = 'unfulfilled'>Unfulfilled</div>
                        <div class = 'item' data-value = 'fulfilled'>Fulfilled</div>
                    </div>
                </div>
            </div>
            <div class = 'field date-fulfilled-container'>
                <label>Date Fulfilled</label>
                <%= purchase_order.date_field :date_fulfilled %>
            </div>
        </div>
        <div class = 'ui bottom attached segment'>
            <%= purchase_order.submit 'Save', class: 'ui primary button' %>
        </div>

         <!-- Hidden Field -->
        <%= purchase_order.text_field :status, hidden: true %>
    <% end %>
</div>

app/views/purchase_orders/index.html.erb
<%= render 'header' %>
<div class = 'container-content view-index'>
    <div class = 'ui segment index-all-records-list-container'>
        <div class = 'ui middle aligned divided very relaxed list index-all-records-list'>
            <div class = 'item list-header'>
                <div class = 'ui column grid content'>
                    <div class = 'row'>
                        <div class = 'wide column col-purchaseDate'>Date</div>
                        <div class = 'wide column col-poDetails'>Purchase Order Details</div>
                        <div class = 'wide column col-status'>Status</div>
                        <div class = 'wide column col-outstandingBal'>Outstanding Bal.</div>
                        <div class = 'wide column col-actions'>Actions</div>
                    </div>
                </div>
            </div>
            <div class = 'scrollable-item-area'>
                <% if @purchase_orders.empty? %>
                    <div class = 'item list-item'>
                        <span><i>No purchase orders to show.</i></span>
                    </div>
                <% else %>
                    <% @purchase_orders.each do |purchase_order| %>
                        <div class = 'item list-item'>
                            <div class = 'ui column grid content'>
                                <div class = 'row'>
                                    <div class = 'wide column col-purchaseDate'>
                                        <span><%= purchase_order.purchase_date.strftime('%b %d, %Y') %></span>
                                    </div>
                                    <div class = 'wide column col-poDetails'>
                                        <div class = 'header'><%= purchase_order.po_num %></div>
                                        <table class = 'details'>
                                            <tbody>
                                                <tr>
                                                    <td class = 'key'>Customer:</td>
                                                    <td class = 'value'><%= purchase_order.customer_account.customer_name %></td>
                                                </tr>
                                                <tr>
                                                    <td class = 'key'>Orders:</td>
                                                    <td class = 'value'>
                                                        <%= purchase_order.products.count.to_s %>
                                                        <%= purchase_order.products.count != 1 ? 'items' : 'item' %>
                                                        <%= ' — '%>
                                                        <% product_names = [] %>
                                                        <% purchase_order.products.each do |product| %>
                                                            <% product_names.push(product.product_name) %>
                                                        <% end %>
                                                        <%= product_names.join('; ') %>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class = 'key'>Total:</td>
                                                    <td class = 'value'>₱ <%= number_with_precision(purchase_order.negotiated_price, precision: 2, delimiter: ',') %></td>
                                                </tr>
                                                <tr>
                                                    <td class = 'key'>Remarks:</td>
                                                    <td class = 'value'>
                                                        <%= purchase_order.remarks != nil && purchase_order.remarks != '' ? purchase_order.remarks : '<i>No Remarks.</i>'.html_safe %>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class = 'wide column col-status'>
                                        <%= purchase_order.status.capitalize %>
                                        <div class = 'single-detail'>
                                            <%= 'on ' + purchase_order.date_fulfilled.strftime('%b %d, %Y') if purchase_order.status == 'fulfilled' %>
                                        </div>
                                    </div>
                                    <div class = 'wide column col-outstandingBal'>
                                        <% if purchase_order.outstanding_balance > 0 %>
                                            <%= number_with_precision(purchase_order.outstanding_balance, precision: 2, delimiter: ',') %>
                                            <div class = 'single-detail'>
                                                <%= 'due on ' + purchase_order.due_date.strftime('%b %d, %Y') if purchase_order.outstanding_balance > 0 %>
                                            </div>
                                        <% else %>
                                            <i>Fully paid.</i>
                                        <% end %>
                                    </div>
                                    <div class = 'wide column col-actions'>
                                        <div class = 'ui small floating dropdown icon button'>
                                            <i class = 'caret down icon'></i>
                                            <div class = 'menu'>
                                                <a class = 'item' href = <%= purchase_order_edit_status_path(purchase_order.id) %>>Update Status</a>
                                                <a class = 'item <%= 'disabled' if purchase_order.outstanding_balance == 0 %>' href = <%= new_customer_payment_path(customer_account_id: purchase_order.customer_account.id, purchase_order_id: purchase_order.id) %>>Add Payment</a>
                                                <div class = 'divider'></div>
                                                <a class = 'item' href = <%= purchase_order_path(purchase_order.id) %>><i class = 'folder open icon'></i>View</a>
                                                <a class = 'item' href = <%= edit_purchase_order_path(purchase_order.id) %>><i class = 'edit icon'></i>Edit</a>
                                                <a class = 'item' href = ''><i class = 'trash icon'></i>Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/purchase_orders/new.html.erb
<%= render 'header' %>
<div class = 'container-content view-new'>
    <div class = 'ui attached message'>
        <div class = 'header'>New Purchase Order</div>
    </div>
    <%= render 'form' %>
</div>

app/views/purchase_orders/show.html.erb
<%= render 'header' %>
<div class = 'container-content view-show'>
    <div class = 'section-messages'>
        <div class = 'section-messages'>
            <%= render '/shared/flash_messages' %>
        </div>
    </div>
    <div class = 'section-content'>
        <div class = 'ui form'>
            <div class = 'ui attached message'>
                <div class = 'header'>View Purchase Order</div>
            </div>
            <div class = 'ui attached segment'>
                <div class = 'customer-information-container'>
                    <div class = 'field'>
                        <label>Purchase Order ID</label>
                        <span><%= @purchase_order.po_num %></span>
                    </div>
                    <div class = 'field'>
                        <label>Customer Account</label>
                        <table class = 'general-details-table'>
                            <tbody>
                                <tr>
                                    <td class = 'key'>Name:</td>
                                    <td class = 'value'><%= @purchase_order.customer_account.customer_name %></td>
                                </tr>
                                <tr>
                                    <td class = 'key'>Address:</td>
                                    <td class = 'value'><%= @purchase_order.customer_account.address %></td>
                                </tr>
                                <tr>
                                    <td class = 'key'>Email:</td>
                                    <td class = 'value'><%= @purchase_order.customer_account.email %></td>
                                </tr>
                                <tr>
                                    <td class = 'key'>Tel. No.:</td>
                                    <td class = 'value'><%= @purchase_order.customer_account.telephone_number %></td>
                                </tr>
                                <tr>
                                    <td class = 'key'>Fax No.:</td>
                                    <td class = 'value'><%= @purchase_order.customer_account.fax_number %></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class = 'ui attached segment'>
                <div class = 'ui three column grid metadata-container'>
                    <div class = 'row'>
                        <div class = 'custom wide column'>
                            <div class = 'field'>
                                <label>Purchase Date</label>
                                <span><%= @purchase_order.purchase_date.strftime('%b %d, %Y') %></span>
                            </div>
                        </div>
                        <div class = 'custom wide column'>
                            <div class = 'field'>
                                <label>Status</label>
                                <span>
                                    <%= @purchase_order.status.capitalize %>
                                    <%= '— on ' + @purchase_order.date_fulfilled.strftime('%b %d, %Y') if @purchase_order.status == 'fulfilled' %>
                                </span>
                            </div>
                        </div>
                        <div class = 'custom wide column'>
                            <div class = 'field'>
                                <label>Payment Terms</label>
                                <span>
                                    <%= '30 Days' if @purchase_order.payment_terms == '30-days' %>
                                    <%= '60 Days' if @purchase_order.payment_terms == '60-days' %>
                                    <%= '90 Days' if @purchase_order.payment_terms == '90-days' %>
                                    <%= '<i>Paid on Purchase.</i>'.html_safe if @purchase_order.payment_terms == 'paid' %>
                                    <%= '— due ' + @purchase_order.due_date.strftime('%b %d, %Y') if @purchase_order.payment_terms != 'paid' %>
                                </span>
                            </div>
                        </div>
                        <div class = 'custom wide column'>
                            <div class = 'field'>
                                <label>Outstanding Bal.</label>
                                <span>
                                    <% if @purchase_order.outstanding_balance > 0 %>
                                        ₱ <%= number_with_precision(@purchase_order.outstanding_balance, precision: 2, delimiter: ',').to_s + ' remaining' %>
                                    <% else %>
                                        <i>Fully Paid</i>
                                    <% end %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = 'ui attached segment'>
                <div class = 'field'>
                    <label>Orders</label>
                    <div class = 'ui segments'>
                        <div class = 'ui attached segment order-line-table-container'>
                            <table class = 'ui celled striped table'>
                                <thead>
                                    <tr>
                                        <th class = 'col-particulars'>Particulars</th>
                                        <th class = 'col-unit-price'>Unit Price</th>
                                        <th class = 'col-qty'>Qty.</th>
                                        <th class = 'col-order-price'>Order Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @purchase_order.order_lines.each do |order_line| %>
                                        <tr>
                                            <td class = 'col-particulars'><%= @purchase_order.products.find(order_line.product_id).product_name %> </td>
                                            <td class = 'col-unit-price'><%= number_with_precision(@purchase_order.products.find(order_line.product_id).unit_price, precision: 2, delimiter: ',') %></td>
                                            <td class = 'col-qty'><%= order_line.quantity %></td>
                                            <td class = 'col-order-price'><%= number_with_precision(order_line.order_price, precision: 2, delimiter: ',') %></td>
                                        </tr>
                                    <% end %>
                                </tbody> 
                            </table>
                        </div>
                        <div class = 'ui attached segment main-price-container subtotal-info-container'>
                            <div class = 'left-col'>
                                 <span class = 'label'>Subtotal:</span>
                            </div>
                            <div class = 'right-col'>
                                 <span class = 'value'><%= number_with_precision(@purchase_order.subtotal, precision: 2, delimiter: ',') %></span>
                            </div>
                        </div>
                        <div class = 'ui attached segment main-price-container discount-info-container'>
                            <div class = 'left-col'>
                                 <span class = 'label'>Discount:</span>
                            </div>
                            <div class = 'right-col'>
                                <% if @purchase_order.discount > 0 %>
                                    <div class = 'ui basic label'>
                                        <% if @purchase_order.discount_type == 'percent' %>
                                            <%= number_with_precision(((@purchase_order.discount / @purchase_order.subtotal) * 100), precision: 0).to_s + '%'  %>
                                        <% elsif @purchase_order.discount_type == 'amount' %>
                                            <%= 'Exact' %>
                                        <% end %>
                                    </div>
                                <% end %>
                                <span class = 'value'>
                                    <%= number_with_precision(@purchase_order.discount, precision: 2, delimiter: ',') %>
                                </span>
                            </div>
                        </div>
                        <div class = 'ui attached segment total-price-container'>
                            <div class = 'left-col'></div>
                            <div class = 'right-col'>
                                 <span class = 'value'>
                                    <%= '₱ ' + number_with_precision(@purchase_order.negotiated_price, precision: 2, delimiter: ',').to_s %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = 'ui bottom attached segment'>
                <div class = 'field'>
                    <label>Remarks</label>
                    <%= @purchase_order.remarks.blank? ? '<i>No Remarks.</i>'.html_safe : @purchase_order.remarks %>
                </div>
            </div>
        </div>
    </div>
</div>