config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: 'pages#index'
  resources :pages, only: [:index], path: ''
  get '/backup', to: 'pages#backup'

  resources :customer_accounts, path: 'customers'
  resources :purchase_orders, path: 'orders' do
    get '/edit/status', to: 'purchase_orders#edit_status'
  end
  scope '/inventory' do
    resources :products, path: 'products'
    resources :inventory_histories, path: 'updates'
  end
  resources :customer_payments, path: 'payments'

  resources :api, only:[] do
    collection do
        get '/po_for_payment', to: 'api#get_purchase_orders_for_customer_payment'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_lines
    has_many :purchase_orders, through: :order_lines
    has_many :inventory_histories

    validate :validate_input
    
    before_save :sanitize_input

    def remaining_quantity
        result = 0
        self.inventory_histories.each do |inventory_history|
            if inventory_history.action_type.downcase == 'in'
                result += inventory_history.quantity
            else
                result -= inventory_history.quantity
            end
        end
        return result
    end

    private
        def sanitize_input
            
        end
        def validate_input
             # PRODUCT NAME
                if self.product_name.blank?
                    errors.add(:product_name, 'Product Name can\'t be blank.')
                elsif Product.exists?(product_name: self.product_name)
                    errors.add(:product_name, 'Product Name has been taken.')
                end

            # SPECIFICATIONS
                if self.product_specs.blank?
                    errors.add(:product_specs, 'Specifications can\'t be blank.')
                end

            # CLASSIFICATION
                if self.product_type.blank?
                    errors.add(:product_type, 'Classification can\'t be blank.')
                end

            # UNIT PRICE
                if self.unit_price.blank?
                    errors.add(:unit_price, 'Unit Price can\'t be blank.')
                elsif self.unit_price <= 0
                    errors.add(:unit_price, 'Unit Price must be a positive, non-zero value.')
                end
                
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @products = Product.all
    end
    def new
        @product = Product.new
    end
    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to(products_path(@product))
        else
            render :new
        end
    end
    def show
        @product = Product.find(params[:id])
    end
    def edit
        @product = Product.find(params[:id])
    end
    def update

    end

    private
        def product_params
            params.require(:product).permit!
        end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class = 'view-form-partial'>
    <%= form_for @product, html: {class: 'ui form'} do |product| %>
        <div class = 'ui attached segment'>
            <div class = 'required field <%= 'error' if @product.errors[:product_name].empty? == false %>'>
                <%= label_tag :product_name, 'Product Name' %>
                <%= product.text_field :product_name %>
            </div>
            <div class = 'required field <%= 'error' if @product.errors[:product_specs].empty? == false %>'>
                <%= label_tag :product_specs, 'Specifications'%>
                <%= product.text_field :product_specs %>
            </div>
            <div class = 'fields'>
                <div class = 'ten wide field'>
                    <div class = 'required field <%= 'error' if @product.errors[:product_type].empty? == false %>'>
                        <%= label_tag :product_type, 'Classification' %>
                        <%= product.text_field :product_type %>
                    </div>
                </div>
                <div class = 'six wide field'>
                    <div class = 'required field <%= 'error' if @product.errors[:unit_price].empty? == false %>'>
                        <%= label_tag :unit_price, 'Unit Price' %>
                        <%= product.text_field :unit_price %>
                    </div>
                </div>
            </div>
            <div class = 'field'>
                <div class = 'sixteen wide column'>
                    <div class = 'field'>
                        <%= label_tag :description %>
                        <%= product.text_area :description %>
                    </div>
                </div>
            </div>
        </div>
        <div class = 'ui bottom attached segment'>
            <%= product.submit 'Save', class: 'ui primary button' %>
        </div>
    <% end %>
</div>

app/views/products/_header.html.erb
<div class = 'ui vertical segment container-header'>
    <h1>Inventory</h1>
    <div class = 'menu-buttons'>
        <div class = 'ui compact menu header-menu'>
            <a class = 'item' href = <%= inventory_histories_path %>>All Inventory Updates</a>
            <a class = 'item' href = <%= new_inventory_history_path %>><i class = 'add icon'></i>New</a>
        </div>
        <div class = 'ui compact menu header-menu'>
            <a class = 'item' href = <%= products_path %>>All Products</a>
            <a class = 'item' href = <%= new_product_path %>><i class = 'add icon'></i>New</a>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<%= render 'header' %>
<div class = 'container-content view-edit'>
    <div class = 'ui attached message'>
        <div class = 'header'>Edit Product</div>
    </div>
    <%= render 'form' %>
</div>

app/views/products/index.html.erb
<%= render 'header' %>
<div class = 'container-content view-index'>
    <div class = 'ui segment index-all-records-list-container'>
        <div class = 'ui middle aligned divided very relaxed list index-all-records-list'>
            <div class = 'item list-header'>
                <div class = 'ui column grid content'>
                    <div class = 'row'>
                        <div class = 'wide column col-productDetails'>Product Details</div>
                        <div class = 'wide column col-qty'>Quantity</div>
                        <div class = 'wide column col-actions'>Actions</div>
                    </div>
                </div>
            </div>
            <div class = 'scrollable-item-area'>
                <% if @products.empty? %>
                    <div class = 'item list-item'>
                        <span><i>No Products to show.</i></span>
                    </div>
                <% else %>
                    <% @products.each do |product| %>
                        <div class = 'item list-item'>
                            <div class = 'ui column grid content'>
                                <div class = 'row'>
                                    <div class = 'wide column col-productDetails'>
                                        <div class = 'header'><%= product.product_name %></div>
                                        <table = class = 'details'>
                                            <tbody>
                                            <tr>
                                                <td class = 'key'>Classification:</td>
                                                <td class = 'value'><%= product.product_type %></td>
                                            </tr>
                                            <tr>
                                                <td class = 'key'>Specifications:</td>
                                                <td class = 'value'><%= product.product_specs %></td>
                                            </tr>
                                            <tr>
                                                <td class = 'key'>Unit Price:</td>
                                                <td class = 'value'>₱ <%= number_with_precision(product.unit_price, precision: 2, delimiter: ',') %></td>
                                            </tr>
                                            <tr>
                                                <td class = 'key'>Description:</td>
                                                <td class = 'value'>
                                                    <%= product.description != nil && product.description != '' ? product.description : '<i>No Description.</i>'.html_safe %>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class = 'wide column col-qty'>
                                        <%= product.remaining_quantity %>
                                    </div>
                                    <div class = 'wide column col-actions'>
                                        <div class = 'ui small floating dropdown icon button'>
                                            <i class = 'caret down icon'></i>
                                            <div class = 'menu'>
                                                <a class = 'item' href = <%= new_inventory_history_path(product_id: product.id) %>>Update Qty.</a>
                                                <div class = 'divider'></div>
                                                <a class = 'item' href = <%= product_path(product.id) %>><i class = 'folder open icon'></i>View</a>
                                                <a class = 'item' href = <%= edit_product_path(product.id) %>><i class = 'edit icon'></i>Edit</a>
                                                <a class = 'item' href = ''><i class = 'trash icon'></i>Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<%= render 'header' %>
<div class = 'container-content view-new'>
    <div class = 'section-messages'>
        <% if @product.errors.any? %>
            <%= render '/shared/form_error_messages', object: @product %>
        <% end %>
    </div>
    <div class = 'section-content'>
        <div class = 'ui attached message'>
            <div class = 'header'>New Product</div>
        </div>
        <%= render 'form' %>
    </div>
</div>

app/views/products/show.html.erb
<%= render 'header' %>
<div class = 'container-content view-show'>
    <div class = 'section-messages'>
        <%= render '/shared/flash_message' %>
    </div>
    <div class = 'section-content'>
        <div class = 'ui attached message'>
            <div class = 'header'>View Product</div>
        </div>
        <div class = 'ui bottom attached segment'>
            <div class = 'ui form'>
                <div class = 'field'>
                    <label>Name</label>
                    <span><%=  @product.product_name %></span>
                </div>
                <div class = 'field'>
                    <label>Classification</label>
                    <span><%=  @product.product_type %></span>
                </div>
                <div class = 'field'>
                    <label>Specifications</label>
                    <span><%=  @product.product_specs %></span>
                </div>
                <div class = 'field'>
                    <label>Description</label>
                    <span><%= @product.description.blank? ? '<i>No Description.</i>'.html_safe : @product.description %></span>
                </div>
                <div class = 'field'>
                    <label>Unit Price</label>
                    <span>₱ <%= number_with_precision(@product.unit_price, precision: 2, delimiter: ',') %></span>
                </div>
            </div>
        </div>
    </div>
</div>