config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: 'pages#index'
  resources :pages, only: [:index], path: ''
  get '/backup', to: 'pages#backup'

  resources :customer_accounts, path: 'customers'
  resources :purchase_orders, path: 'orders' do
    get '/edit/status', to: 'purchase_orders#edit_status'
  end
  scope '/inventory' do
    resources :products, path: 'products'
    resources :inventory_histories, path: 'updates'
  end
  resources :customer_payments, path: 'payments'

  resources :api, only:[] do
    collection do
        get '/po_for_payment', to: 'api#get_purchase_orders_for_customer_payment'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accuratech IIS</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag params[:controller] %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag params[:controller] %>

  </head>
  <body>
  <% if user_signed_in? %>
    <div class = 'ui left vertical menu visible inverted sidebar'>
      <div class = 'item'>
        <div class = 'header'>ACCURATECH IIS</div>
      </div>
      <div class = 'item'>
        <div class = 'header'>Quick Links</div>
        <div class = 'menu'>
          <a class = 'item' href = <%= new_purchase_order_path %>>Add Purchase Order</a>
          <a class = 'item' href = <%= new_customer_payment_path %>>Add Customer Payment</a>
        </div>
      </div>
      <div class = 'item'>
        <div class = 'header'>Dashboard</div>
        <div class = 'menu'>
          <a class = 'item' href = <%= pages_path %>>Home</a>
          <a class = 'item' href = <%= products_path %>>Inventory</a>
          <a class = 'item' href = <%= purchase_orders_path %>>Purchase Orders</a>
          <a class = 'item' href = <%= customer_payments_path %>>Customer Payments</a>
          <a class = 'item' href = <%= customer_accounts_path %>>Customer Accounts</a>
        </div>
      </div>
      <div class = 'item'>
        <div class = 'header'>Settings</div>
        <div class = 'menu'>
          <a class = 'item' href = <%= backup_path %>>Backup</a>
        </div>
      </div>
    </div>
    <div class = 'pusher view-content-container'>
      <div class = 'top-content'>
        <span class = 'system-info'>
          Integrated Inventory System
        </span>
        <span class = 'login-info'>
          Logged-in as <%= (' <b>' + current_user.email.to_s + '</b>').html_safe %>
          &nbsp; &nbsp; &nbsp;
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </span>
      </div>
      <div class = 'center-content'>
        <%= yield %>
      </div>
    </div>
  <% else %>
    <%= yield %>
  <% end %>
  </body>
</html>